version: "2"

linters:
  default: standard
  enable:
    - gostructfmt
  settings:
    custom:
      gostructfmt:
        type: module
        description: Check populated Go struct literals for gostructfmt formatting.
        original-url: github.com/goropikari/gostructfmt
